name: Main CI Workflow

on:
  push:
    branches:
      - main
      - 'hotfix/**'
      - 'release/**'
    tags:
      - '*'
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Hello
        run: |
          echo "Hello, world!"
